# Generated by Django 3.2 on 2023-03-18 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='confirmation_token',
            new_name='confirmation_code',
        ),
    ]
