# Generated by Django 3.2 on 2023-03-19 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20230319_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(editable=False, max_length=20, null=True, unique=True),
        ),
    ]
